name: Official Devices Workflow
on:
  push:
   
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: Send telegram channel update message
          run: |
            sudo apt install jq -y
            echo "${{ secrets.tg_token }}" > ~/.telegram.sh
            export raws=$(git log -1 | grep update | awk '{ print $2 " " $3}')
            for raw in $raws; do
                export official_devices_json=$(curl https://raw.githubusercontent.com/lighthouse-os/official_devices/main/official_devices.json)
                for row in $(echo "${official_devices_json}" | jq -r '.[] | @base64'); do
                    _jq() {
                        echo ${row} | base64 --decode | jq -r ${1}
                    }
                    export name=$(_jq '.codename')
                    if [ "$name" = "$raws" ]; then
                        export version_code=$(_jq ".supported_versions[].version_code")
                    fi
                done
                curl https://raw.githubusercontent.com/lighthouse-os/official_devices/$version_code/builds/$raw.json -o $device.json
                export json=$device.json
                export device=$( jq ".device" $json | sed s/'"'//g)
                export filename=$( jq ".filename" $json | sed s/'"'//g)
                export changelog="https://raw.githubusercontent.com/lighthouse-os/official_devices/$version_code/changelogs/$device/$filename.txt"
                export version=$( jq ".version" $json | sed s/'"'//g)
                export size=$( jq ".size" $json | sed s/'"'//g)
                export size=$(bc -l <<< $size/1000000000 | head -c -19)
                echo $size
                git clone https://github.com/fabianonline/telegram.sh.git && sudo mv telegram.sh/telegram /usr/bin && rm -rf telegram.sh
                if [ ! -z $device ];then
                 jq -c '.[]' official_devices.json | while read i; do
                      codename=$(echo $i | jq '.codename'| sed s/'"'//g)
                      if [ "$codename" = "$device" ];then
                          export maintainer_name=$(echo $i | jq '.supported_versions[0].telegram_id'| sed s/'"'//g)
                          export maintainer_id=$(echo $i | jq '.supported_versions[0].telegram_id'| sed s/'"'//g)
                          export url=$(echo $i | jq '.pling'| sed s/'"'//g)
                          telegram -c -1001389774529 -i ./banner.png -M  "*     | TEST BANNER, NOT AN UPDATE! |*"$'\n'"• *Download:* [$device]($url)"$'\n'"• *Size: $size GB*"$'\n'"• Maintainer: [$maintainer_name](https://t.me/$maintainer_id)"$'\n'"• *CL:* [$filename]($changelog)"$'\n'"• [Channel](https://t.me/project_lighthouse)"$'\n'"• [Rom Support](https://t.me/project_lighthouse_os)"
                      fi
                 done
                fi
            done
